version: '3.9'
services:
  pets_app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_USERNAME=fuentech
      - MONGO_PASS=admin
      - MONGO_HOST=mongo_db_dev
    links:
      - mongo_db_dev
    volumes:
      - .:/home/app
  mongo_db_dev:
    image: mongo:8.0-rc
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fuentech
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data-dev:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data-dev:
