services:
  node:
    # container_name: pets_app
    depends_on:
      mongo:
        condition: service_started
        restart: true
    build: .
    image: fuentech/pets-app:1
    restart: always
    env_file: ./.env
    ports:
      - $LOCAL_NODE_PORT:$DOCKER_NODE_PORT
    #links:
    # - mongo

  mongo:
    image: mongo:8.0-rc
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fuentech
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - $LOCAL_MONGO_PORT:$DOCKER_MONGO_PORT
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data:
