version: '3.9'
services:
  pets_app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_USERNAME=fuentech
      - MONGO_PASS=admin
      - MONGO_HOST=mongo_db
    links:
      - mongo_db
  mongo_db:
    image: mongo:8.0-rc
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fuentech
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data:
