version: '3.9'
services:
  pets_app_dev:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/home/app
  mongo:
    env_file:
      - .env
    image: mongo:8.0-rc
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-dev:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data-dev:
